# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :systemd => {
        :box_name => "centos/7",
	:box_version => "1804.02",
        :ip_addr => '192.168.11.101'
        },
   }
   
Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
	config.vm.box_version = "1804.02"
	config.vm.define boxname do |box|
         box.vm.box = boxconfig[:box_name]
         box.vm.host_name = boxname.to_s
         box.vm.network "private_network", ip: boxconfig[:ip_addr]
         box.vm.provider :virtualbox do |vb|
           	  vb.customize ["modifyvm", :id, "--memory", "1024"]
end
	 box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
	
 

# Ставим apache
yum install -y httpd

# Создаём наш unit-file
cp /usr/lib/systemd/system/httpd.service /etc/systemd/system/httpd@.service

# Создаём шаблон unit - httpd
sed -i.orig s@sysconfig/httpd@sysconfig/httpd-%I@ /etc/systemd/system/httpd@.service

# 2 файла конфигурации для старта апача по шаблону @
cp /etc/sysconfig/httpd /etc/sysconfig/httpd-first
cp /etc/sysconfig/httpd /etc/sysconfig/httpd-second

# -f -> опция, указывающая путь к файлу конфигурации cat /etc/sysconfig/httpd-first
# Редактируем
sed -i.orig 's@^#OPTIONS=@OPTIONS="-f conf/first.conf"@' /etc/sysconfig/httpd-first
sed -i.orig 's@^#OPTIONS=@OPTIONS="-f conf/second.conf"@' /etc/sysconfig/httpd-second

# Создаём 2 httpd файла конфигурации для шаблона @ first.conf +  second.conf
cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/first.conf
cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/second.conf

# Меняем pid-файл и слушаем другой порт вместо 80 для апача
# Для новых конфигураций апача назначаем разные pid файлы и прослушиваемые порты для каждого инстанса
sed -i.orig "s/^Listen 80/Listen 8009/" /etc/httpd/conf/first.conf
echo 'PidFile /var/run/httpd-first.pid' >> /etc/httpd/conf/first.conf

sed -i.orig "s/^Listen 80/Listen 8008/" /etc/httpd/conf/second.conf
echo 'PidFile /var/run/httpd-second.pid' >> /etc/httpd/conf/second.conf

# Стартуем два инстанса шаблонов @
systemctl start httpd@second
systemctl start httpd@first
ss -tnulp | grep httpd

        SHELL
	 end
	end
end
